## Preprocessing of Data

This nootebook explores the preprocessing of Data.

## Import libraries and load raw data

In [ ]:
import pandas as pd

# Load dataset
file_path = "../Dataset_Cities.csv"
data = pd.read_csv(file_path)

# Display first few rows
data.head()

,country,state,city,station,last_update,latitude,longitude,pollutant_id,pollutant_min,pollutant_max,pollutant_avg
0,India,Bihar,Aurangabad,"Gurdeo Nagar, Aurangabad - BSPCB",28-08-2025 19:00:00,24.75746,84.366208,PM10,25.0,166.0,73.0
1,India,Bihar,Begusarai,"Lohiyanagar, Begusarai - BSPCB",28-08-2025 19:00:00,25.42742,86.138861,NH3,3.0,4.0,4.0
2,India,Bihar,Bettiah,"Kamalnath Nagar, Bettiah - BSPCB",28-08-2025 19:00:00,26.80365,84.519540,PM10,5.0,59.0,32.0
3,India,Bihar,Bettiah,"Kamalnath Nagar, Bettiah - BSPCB",28-08-2025 19:00:00,26.80365,84.519540,NO2,5.0,12.0,8.0
4,India,Bihar,Bettiah,"Kamalnath Nagar, Bettiah - BSPCB",28-08-2025 19:00:00,26.80365,84.519540,CO,39.0,75.0,59.0

## Handle missing values

In [2]:
# Check missing values
print(data.isnull().sum())

# Fill numerical columns with median
num_cols = data.select_dtypes(include=['int64', 'float64']).columns
data[num_cols] = data[num_cols].fillna(data[num_cols].median())

# Fill categorical columns with mode
cat_cols = data.select_dtypes(include=['object']).columns
for col in cat_cols:
    data[col] = data[col].fillna(data[col].mode()[0])

print("Missing values handled.")

country            0
state              0
city               0
station            0
last_update        0
latitude           0
longitude          0
pollutant_id       0
pollutant_min    269
pollutant_max    269
pollutant_avg    269
dtype: int64
Missing values handled.

## Encode categorical features

In [3]:
# Encode categorical variables using one-hot encoding
data_encoded = pd.get_dummies(data, drop_first=True)

print("Categorical features encoded.")
data_encoded.head()

Categorical features encoded.

,latitude,longitude,pollutant_min,pollutant_max,pollutant_avg,state_Arunachal_Pradesh,state_Assam,state_Bihar,state_Chandigarh,state_Chhattisgarh,...,"station_Yamunapuram, Bulandshahr - UPPCB","station_Yerramukkapalli, Kadapa - APPCB","station_Zero Point GICI, Gangtok - SSPCB","station_Zoo Park, Hyderabad - TSPCB",pollutant_id_NH3,pollutant_id_NO2,pollutant_id_OZONE,pollutant_id_PM10,pollutant_id_PM2.5,pollutant_id_SO2
0,24.75746,84.366208,25.0,166.0,73.0,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
1,25.42742,86.138861,3.0,4.0,4.0,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,False
2,26.80365,84.519540,5.0,59.0,32.0,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,26.80365,84.519540,5.0,12.0,8.0,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,False
4,26.80365,84.519540,39.0,75.0,59.0,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False